key_list = [
	'C',
	'Cm',
	'C#',
	'C#m',
	'Db',
	'Dbm',
	'D',
	'Dm',
	'D#',
	'D#m',
	'Eb',
	'Ebm',
	'E',
	'Em',
	'F',
	'Fm',
	'F#',
	'F#m',
	'Gb',
	'Gbm',
	'G',
	'Gm',
	'G#',
	'G#m',
	'Ab',
	'Abm',
	'A',
	'Am',
	'A#',
	'A#m',
	'Bb',
	'Bbm',
	'B',
	'Bm',
]

scales = {
    "major": {'halfsteps': (2,2,1,2,2,2,1), 'major': True},
    "minor": {'halfsteps': (2,1,2,2,1,2,2), 'major': False},
    "dorian": {'halfsteps': (2,1,2,2,2,1,2), 'major': False},
    "dominant": {'halfsteps': (2,2,1,2,2,1,2), 'major': True},
    "harmonic minor": {'halfsteps': (2,1,2,2,1,3,1), 'major': False},
    "blues": {'halfsteps': (3,2,1,1,3,2), 'major': False},
    "major blues": {'halfsteps': (2,1,1,3,2,3), 'major': True},
    "minor pentatonic": {'halfsteps': (3,2,2,3), 'major': False},
    "major pentatonic": {'halfsteps': (2,2,3,3), 'major': True},
    "whole tone": {'halfsteps': (2,2,2,2,2,2), 'major': True},
    "chromatic": {'halfsteps': (1,1,1,1,1,1,1,1,1,1,1,1), 'major': False}
}
